# Generated by Django 3.1.2 on 2020-12-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Class', models.CharField(max_length=8)),
                ('school', models.CharField(max_length=15)),
                ('roll', models.IntegerField(max_length=1000)),
            ],
        ),
    ]
