# Generated by Django 3.1.2 on 2020-12-10 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='Class',
            new_name='Last_Name',
        ),
        migrations.RemoveField(
            model_name='form',
            name='roll',
        ),
        migrations.RemoveField(
            model_name='form',
            name='school',
        ),
        migrations.AddField(
            model_name='form',
            name='Email_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
