# Generated by Django 3.1.2 on 2020-12-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coders', '0002_auto_20201210_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='digi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=None)),
                ('title', models.CharField(max_length=12)),
                ('description', models.CharField(max_length=50)),
                ('rate', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='graphic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=None)),
                ('title', models.CharField(max_length=12)),
                ('description', models.CharField(max_length=50)),
                ('rate', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=None)),
                ('title', models.CharField(max_length=12)),
                ('description', models.CharField(max_length=50)),
                ('rate', models.IntegerField(max_length=20)),
            ],
        ),
    ]
